import type { INodePropertyOptions } from 'n8n-workflow';

export const webhookEventOptions: INodePropertyOptions[] = [
  { name: 'Contact Created', value: 'contact.created' },
  { name: 'Contact Deleted', value: 'contact.deleted' },
  { name: 'Contact Topics Updated', value: 'contact.topics.updated' },
  { name: 'Contact Updated', value: 'contact.updated' },
  { name: 'Domain Created', value: 'domain.created' },
  { name: 'Domain Deleted', value: 'domain.deleted' },
  { name: 'Domain Updated', value: 'domain.updated' },
  { name: 'Email Bounced', value: 'email.bounced' },
  { name: 'Email Clicked', value: 'email.clicked' },
  { name: 'Email Complained', value: 'email.complained' },
  { name: 'Email Delivered', value: 'email.delivered' },
  { name: 'Email Delivery Delayed', value: 'email.delivery_delayed' },
  { name: 'Email Failed', value: 'email.failed' },
  { name: 'Email Opened', value: 'email.opened' },
  { name: 'Email Received', value: 'email.received' },
  { name: 'Email Scheduled', value: 'email.scheduled' },
  { name: 'Email Sent', value: 'email.sent' },
  { name: 'Email Suppressed', value: 'email.suppressed' },
  { name: 'Inbox Created', value: 'inbox.created' },
  { name: 'Inbox Deleted', value: 'inbox.deleted' },
  { name: 'Inbox Draft Created', value: 'inbox.draft.created' },
  { name: 'Inbox Draft Deleted', value: 'inbox.draft.deleted' },
  { name: 'Inbox Draft Sent', value: 'inbox.draft.sent' },
  { name: 'Inbox Draft Updated', value: 'inbox.draft.updated' },
  { name: 'Inbox Email Received', value: 'inbox.email.received' },
  { name: 'Inbox Email Sent', value: 'inbox.email.sent' },
  { name: 'Inbox Thread Assigned', value: 'inbox.thread.assigned' },
  { name: 'Inbox Thread Created', value: 'inbox.thread.created' },
  {
    name: 'Inbox Thread Folder Updated',
    value: 'inbox.thread.folder.updated',
  },
  {
    name: 'Inbox Thread Labels Updated',
    value: 'inbox.thread.labels.updated',
  },
  { name: 'Inbox Thread Unassigned', value: 'inbox.thread.unassigned' },
  { name: 'Inbox Updated', value: 'inbox.updated' },
  { name: 'Suppression Added', value: 'suppression.added' },
  { name: 'Suppression Removed', value: 'suppression.removed' },
  { name: 'Topic Created', value: 'topic.created' },
  { name: 'Topic Deleted', value: 'topic.deleted' },
  { name: 'Topic Updated', value: 'topic.updated' },
];
