name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    if: github.event.base_ref == 'refs/heads/master'

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish
        run: npm publish --provenance
